### PR TITLE
WIP: PPC support

### PR DESCRIPTION
**Pull request by h-vetinari**
Based on (a streamlined version of) #18; I want to look into the PPC ICE a bit more.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Ah, this might actually be a libhwy issue after all:
```
[ 44%] Building CXX object lib/CMakeFiles/jxl_enc-obj.dir/jxl/enc_ac_strategy.cc.o
during RTL pass: expand
In file included from $SRC_DIR/lib/jxl/dct-inl.h:21,
                 from $SRC_DIR/lib/jxl/dec_transforms-inl.h:19,
                 from $SRC_DIR/lib/jxl/dec_group.cc:31,
                 from $PREFIX/include/hwy/foreach_target.h:266,   # <--- SEE HERE!
                 from $SRC_DIR/lib/jxl/dec_group.cc:19:
$SRC_DIR/lib/jxl/transpose-inl.h: In function 'void jxl::N_PPC10::{anonymous}::NoInlineWrapper(const T&, const Args& ...) [with T = void(const DCTFrom&, const DCTTo&, long unsigned int, float*); Args = {DCTFrom, DCTTo, long unsigned int, float* __restrict__}]':
$SRC_DIR/lib/jxl/transpose-inl.h:40:11: internal compiler error: in rs6000_sibcall_aix, at config/rs6000/rs6000.cc:25823
   40 |   return f(args...);
      |          ~^~~~~~~~~
```

**Comment by h-vetinari** [comment]
> Ah, this might actually be a libhwy issue after all:

Happens with both libhwy 1.0 & 1.1

**Comment by hmaarrfk** [comment]
i've had trouble with libhwy before on ppc64 i think...

**Comment by hmaarrfk** [comment]
what about removing hwy altogether?

**Comment by hmaarrfk** [comment]
it seems that it wouldn't be the first time that highway would have found ICE in gcc itself:
https://github.com/google/highway/issues?q=is%3Aissue+ppc64le+is%3Aclosed

**Comment by sshockwave** [comment]
Fixed in #29

**Pull request closed without merging**
